name: cf3d_env
channels:
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.6.15=py37haa95532_0
  - cffi=1.15.0=py37h2bbff1b_1
  - colorama=0.4.5=py37haa95532_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37haa95532_0
  - icu=58.2=ha925a31_3
  - importlib-metadata=4.11.3=py37haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.9.1=py37haa95532_0
  - ipython=7.31.1=py37haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.4.0=py37haa95532_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=7.2.2=py37haa95532_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - markupsafe=2.1.1=py37h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37hfa6e2cd_1001
  - nbclient=0.5.13=py37haa95532_0
  - nbconvert=6.4.4=py37haa95532_0
  - nbformat=5.3.0=py37haa95532_0
  - nest-asyncio=1.5.5=py37haa95532_0
  - notebook=6.4.11=py37haa95532_0
  - openssl=1.1.1q=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py37haa95532_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37hd77b12b_6
  - pyrsistent=0.18.0=py37h196d8e1_0
  - python=3.7.13=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - pywin32=302=py37h2bbff1b_2
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyzmq=23.2.0=py37hd77b12b_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.3.1=py37haa95532_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py37haa95532_0
  - sip=4.19.13=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=h2bbff1b_0
  - terminado=0.13.1=py37haa95532_0
  - testpath=0.6.0=py37haa95532_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.8.0=py37haa95532_0
  - zlib=1.2.12=h8cc25b3_2
  - pip:
    - clang==11.0
    - mpmath==1.2.1
    - numpy==1.21.6
    - sympy==1.10.1
